name: mitproxy_val
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  get:
  http:
  shimmer: ^3.0.0
  connectivity_plus:
  shared_preferences: any
  dash_chat_2: ^0.0.19
  cupertino_icons: ^1.0.2
  flutter_dotenv: any
  introduction_screen: ^3.1.14
  url_launcher: any
  video_player: ^2.8.6
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  cached_network_image: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/val_logo_red.png
    - assets/jett.png
    - assets/raze.png
    - assets/vanguard.png
    - assets/kayo_potrait.png
    - assets/jett_banner.jpeg
    - lib/.env